### ISSUE TITLE
about the table of contents

### ISSUE THREAD

**Issue by IanFla** [monaen/HKU-Thesis-Template#1]
How to delete the 'Abstract' and add the 'Table of Contents' in the table of contents? (https://github.com/monaen/HKU-Thesis-Template/blob/master/Others/table_of_contents.png)

Thanks!

**Comment by monaen** [comment]
Hi lanFla,

Thanks for your question.

To remove the ‘Abstract’ chapter from table of contents:  you can just comment this line of code
_\addchaptertocentry{\abstractname}_
in the Abstract/abstract.tex file
![image](https://user-images.githubusercontent.com/16679522/155461558-f333ee14-7eab-46d3-9e7d-438c58ae9092.png)

To add 'Table of Contents', you can uncomment the toctotoc arguments settings in main.tex file.
![image](https://user-images.githubusercontent.com/16679522/155461958-5fcf0306-4191-45d9-b106-5e567ebeff86.png)

If you are not satisfied with the name 'Contents', you can change the parameter '\contentsname' from the style setting file HKUThesis.cls
![4343534534534534](https://user-images.githubusercontent.com/16679522/155463166-d5d4410a-211d-4af2-96fe-dcb2b24cc69c.PNG)
You can replace '\contentsname' directly or give it a new value which is a string to be appeared in the TOC.

Best regards,

Nan

**Comment by monaen** [comment]
Hope this resolve your problem.

**Comment by IanFla** [comment]
Thanks very much!

BRs,
ZHANG Yan

Nan Meng ***@***.***> 于2022年2月24日周四 13:26写道：
