### ISSUE TITLE
about the subsubsection

### ISSUE THREAD

**Issue by IanFla** [monaen/HKU-Thesis-Template#2]
How to number the subsubsection?

There is no number in the template: 
<img width="597" alt="截屏2022-02-24 下午7 19 19" src="https://user-images.githubusercontent.com/51277149/155514719-4555eebf-86df-4bd5-ad12-537697a4c6ee.png">

This is the Guide:
<img width="597" alt="截屏2022-02-24 下午7 19 30" src="https://user-images.githubusercontent.com/51277149/155514750-787ea1f8-2ddb-4485-ae49-102b9550b3f1.png">

**Comment by monaen** [comment]
Hi lanFla,

This is a default setting, not only for this template.
If you want to number the subsubsection, the simplest solution is to add one line of code somewhere in main.tex
For example, I add the code directly before the \begin{document}
![image](https://user-images.githubusercontent.com/16679522/155522072-1689db08-65ea-4aaa-a475-a8d86bbf22c8.png)

The compiled result:
![image](https://user-images.githubusercontent.com/16679522/155522241-9da4e57a-d1fe-449f-98d2-114966886617.png)

**Comment by IanFla** [comment]
nice! thanks!
