### ISSUE TITLE
Warning in Legacy month field

### ISSUE THREAD

**Issue by Billy-Fudan** [monaen/HKU-Thesis-Template#3]
Overleaf has multiple warnings after compiling, most of which are caused by the legacy month field, shown below
![微信图片_20220505122205](https://user-images.githubusercontent.com/8359623/166863299-5007f990-24d7-4e47-ae44-c2d5391d22cb.png)

**Comment by monaen** [comment]
Hi,
Thanks for your question.

This one is a warning for the month item. According to the document `biblatex` [package documentation](https://mirror.informatik.hs-fulda.de/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf)


>**month**
The publication month. This must be an integer, not an ordinal or a string. Don’t say `month={January}` but `month={1}`. 
The bibliography style converts this to a language dependent string or ordinal where required. 
This field is a literal field only when given explicitly in the data (for plain BibTeX compatibility for example).
(see page 24)

You should change the string to the integer

Hope this helps!

Best,

Nan
